[package]
name = "das_keyboard_github_service"
version = "0.1.0"
authors = ["Mathieu <MathieuKeller@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0-beta.1"
actix-service = "2.0.0-beta.3"
futures = "0.3.9"
env_logger = "0.8.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.61"
json = "0.12.4"
reqwest = { version = "0.11", features = ["blocking", "json"] }

[dev-dependencies]
actix-rt = "2.0.0-beta.2"
